### ISSUE TITLE
[DOC] - Doesn't say where the lore lives 

### ISSUE THREAD

**Issue by a2937** [naomi-lgbt/lore#15]
### What is incorrect in the documentation?

If it's deployed on GitHub pages, you should tell us where the application lives 

### What should that text say?

The text should probably say something like "Live at naomi-lgbt.github.io/lore". 

### Additional information

It's probably a good idea to not leave the template text in a frequently updated application.

**Comment by naomi-lgbt** [comment]
Whoops - yeah, it shouldn't be using the angular default readme.

Should just grab my usual readme template and fill it in, tbh.
